# Generated by Django 4.1 on 2022-08-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0003_subscription_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="products/%Y/%m/%d", verbose_name="Фотография"
            ),
        ),
    ]
