# Generated by Django 4.1 on 2022-08-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0004_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="phone_number_0",
            field=models.CharField(max_length=10),
        ),
    ]
