# Generated by Django 4.1 on 2022-08-24 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0005_alter_phonenumber_phone_number_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Post_category",
                to="oskon.subcategory",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subscription",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Subscription",
                to="oskon.post",
            ),
        ),
    ]
