# Generated by Django 4.1 on 2022-08-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0006_post_category_alter_subscription_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="Post_category",
                to="oskon.category",
            ),
        ),
    ]
