# Generated by Django 4.1 on 2022-08-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0007_alter_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
