# Generated by Django 4.1 on 2022-08-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0008_alter_post_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="views",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Post1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "views",
                    models.ManyToManyField(
                        blank=True, related_name="post_views", to="oskon.ip"
                    ),
                ),
            ],
        ),
    ]
