# Generated by Django 4.1 on 2022-08-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0009_ip_alter_views_views_post1"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
