# Generated by Django 4.1 on 2022-09-01 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0010_post_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="HitCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=40)),
                ("session", models.CharField(max_length=40)),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UrlHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("hits", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="post1",
            name="views",
        ),
        migrations.AddField(
            model_name="views",
            name="user_id",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Ip",
        ),
        migrations.DeleteModel(
            name="Post1",
        ),
        migrations.AddField(
            model_name="hitcount",
            name="url_hit",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="oskon.urlhit",
            ),
        ),
    ]
