# Generated by Django 4.1 on 2022-09-01 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0011_hitcount_urlhit_remove_post1_views_views_user_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HitCount",
        ),
        migrations.DeleteModel(
            name="UrlHit",
        ),
    ]
