# Generated by Django 4.1 on 2022-09-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0012_delete_hitcount_delete_urlhit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="views",
            name="user_id",
        ),
        migrations.AddField(
            model_name="views",
            name="user",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
