# Generated by Django 4.1 on 2022-09-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0013_remove_views_user_id_views_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="views",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="views",
            name="user",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="views",
            name="views",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
