# Generated by Django 4.1 on 2022-09-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0014_alter_views_date_alter_views_user_alter_views_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="views",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
