# Generated by Django 4.1 on 2022-09-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0015_alter_views_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="views",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
