# Generated by Django 4.1 on 2022-09-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0016_alter_views_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Baza_view",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_or_user", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
