# Generated by Django 4.1 on 2022-09-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0017_baza_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="baza_view",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
