# Generated by Django 4.1 on 2022-09-10 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0018_baza_view_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="baza_view",
            name="view_key",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baza",
                to="oskon.views",
            ),
            preserve_default=False,
        ),
    ]
