# Generated by Django 4.1 on 2022-09-11 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0019_baza_view_view_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baza_view",
            name="view_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baza",
                to="oskon.post",
            ),
        ),
    ]
