# Generated by Django 4.1 on 2022-09-11 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0020_alter_baza_view_view_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="views",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Views_Post",
                to="oskon.post",
            ),
        ),
    ]
