# Generated by Django 4.1 on 2022-09-14 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0021_alter_views_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="views",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Views_Post",
                to="oskon.post",
            ),
        ),
    ]
