# Generated by Django 4.1 on 2022-09-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0023_phonenumber_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="phone_number_0",
            field=models.CharField(default=500000000, max_length=10),
        ),
    ]
