# Generated by Django 4.1 on 2022-09-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0024_alter_phonenumber_phone_number_0"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewsContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("views", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "phone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        to="oskon.phonenumber",
                    ),
                ),
            ],
        ),
    ]
