# Generated by Django 4.1 on 2022-09-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0025_viewscontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="views",
            name="user",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
