# Generated by Django 4.1 on 2022-09-16 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0026_alter_views_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewscontact",
            name="view_key",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view",
                to="oskon.views",
            ),
            preserve_default=False,
        ),
    ]
