# Generated by Django 4.1 on 2022-09-16 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0030_alter_viewscontact_view_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewscontact",
            name="view_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_contact",
                to="oskon.views",
            ),
        ),
    ]
