# Generated by Django 4.1 on 2022-09-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0032_alter_viewscontact_view_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="phonenumber",
            old_name="phone_number_0",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="post",
            name="phone_number",
        ),
    ]
