# Generated by Django 4.1 on 2022-09-17 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0033_rename_phone_number_0_phonenumber_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonenumber",
            name="post_number",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_post",
                to="oskon.post",
            ),
            preserve_default=False,
        ),
    ]
