# Generated by Django 4.1 on 2022-09-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0034_phonenumber_post_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="viewscontact",
            name="view_key",
        ),
    ]
