# Generated by Django 4.1 on 2022-09-17 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oskon", "0035_remove_viewscontact_view_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewscontact",
            name="view_key",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_post",
                to="oskon.post",
            ),
            preserve_default=False,
        ),
    ]
